typography_spectrum: 0.9460804515983909
color:
  brandColors: []
  brandStrength: 0.7279868023470044
  lightness: 0.6830721667502075
  saturation: 0.4162993719801307
  rhythmicContrast: 0.11573366587981582
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.43141622259281576
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jorge Raymund Maravilla
  email: vicissitude24@gmail.com
  url: thegrid.ai/maravilla
name: Maravilla Chronicles
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: This accounts my online portfolio
purpose: []
